### ISSUE TITLE
Cannot specify link libraries for target "ssh-shell" which is not built by this project.

### ISSUE THREAD

**Issue by va771** [sandsmark/QSsh#15]
CMake throws error while build:
`CMake Error at examples/ssh-shell/CMakeLists.txt:4 (target_link_libraries):
  Cannot specify link libraries for target "ssh-shell" which is not built by
  this project.`

There is a typo in examples/ssh-shell/CMakeLists.txt
`add_executable(ssh-hell argumentscollector.cpp  main.cpp  shell.cpp)`
**ssh-shell** should be :)

**Comment by meteoricfarm** [comment]
use the command 'qmake ../qssh.pro' instead of 'cmake ..'
